version: 2

models:
  - name: stg_customers
    description: "Staging model for customers"
    columns:
      - name: customer_id
        description: "Primary key for customers"
        tests:
          - unique
          - not_null

  - name: stg_orders
    description: "Staging model for orders"
    columns:
      - name: order_id
        description: "Primary key for orders"
        tests:
          - unique
          - not_null
      - name: customer_id
        description: "Foreign key to customers"
